[theme]
base = "dark"
primaryColor = "#4C8F70"              # verde Natureba destacado
backgroundColor = "#1B2621"           # fundo escuro
secondaryBackgroundColor = "#2C3E2D"  # cart√µes/sidebars com contraste leve
textColor = "#F5FAF5"                 # texto claro para ler no fundo escuro
font = "Inter, sans-serif"
